version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3001:3000"  
  backend:
    build: 
      context: .
      dockerfile: ./server/Dockerfile    
    ports:
      - "3000:3000"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sql12345@
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ../sql_server_data:/var/opt/mssql
